// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monitor.Server.Data;

#nullable disable

namespace Monitor.Server.Migrations
{
    [DbContext(typeof(MonitorDbContext))]
    partial class MonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Monitor.Server.Models.ServerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackCpu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackDisk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackRam")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServerConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
